load_paths:
  - src
  - test/src

logical_paths:
  - details-element-polyfill.js
  - test.js

build:
  logical_paths:
    - details-element-polyfill.js
  path: dist
  js_compressor: uglifier

plugins:
  sauce_labs:
    browsers:
      Google Chrome:
        version: -3
      Firefox:
        version: -3
      Safari:
        platform: Mac
        version: -3
      Microsoft Edge:
        version: -2
      Internet Explorer:
        version: -2
